"""Pydantic models for ESB OMS API."""

from esb_oms.models.auth import LoginRequest, LoginResult, TokenInfo
from esb_oms.models.common import ESBBaseModel
from esb_oms.models.master import (
    Branch,
    BranchVisitPurpose,
    BusinessHour,
    MenuCategory,
    MenuCategoryDetail,
    MenuPackageGroup,
    PaymentMethodItem,
    PaymentMethodType,
    POSMenuItem,
    StockBranchItem,
    VisitPurpose,
)
from esb_oms.models.member import GetMemberResponse, MemberResult
from esb_oms.models.menu import (
    CreateMenuCategoryRequest,
    CreateMenuRequest,
    CreateMenuTemplateRequest,
    GetMenuCategoryResponse,
    GetMenuResponse,
    GetMenuTemplateResponse,
    MenuCategoryDetailInput,
    MenuCategoryResult,
    MenuExtraInput,
    MenuIconInput,
    MenuPackageGroupInput,
    MenuPackageMenuInput,
    MenuResult,
    MenuTagInput,
    MenuTemplateDetailInput,
    MenuTemplateDetailResult,
    MenuTemplatePriceInput,
    MenuTemplateResult,
    RelatedMenuInput,
    UpdateMenuCategoryRequest,
    UpdateMenuRequest,
    UpdateMenuTemplateRequest,
)
from esb_oms.models.other import (
    BranchSalesSummaryItem,
    DailySalesMaterialUsageItem,
    SalesDetailItem,
    SalesExtraItem,
    SalesMenuDetailItem,
    SalesPackageItem,
    SalesPaymentDetailItem,
)
from esb_oms.models.promotion import (
    ApplyDiscountTo,
    ApplyTo,
    CreateDiscountAmountESORequest,
    CreateDiscountLimitPercentageRequest,
    CreateDiscountPercentageESORequest,
    CreateDiscountPercentageRequest,
    CreateFreeItemRequest,
    CreatePromotionResponse,
    CreatePromotionResult,
    PaymentMethodResult,
    PromotionBranchResult,
    PromotionCategoryResult,
    PromotionDay,
    PromotionResult,
    PromotionTimeInput,
    PromotionType,
    SelfOrderPaymentMethodResult,
)
from esb_oms.models.report import (
    GetSalesMenuSummaryResponse,
    GetSalesPaymentSummaryResponse,
    MenuSummaryItem,
    PaymentSummaryItem,
    SalesHeadItem,
    SalesInformationItem,
    SalesMenuCompletionItem,
    SalesMenuReportExtraItem,
    SalesMenuReportItem,
    SalesMenuReportPackageItem,
    SalesMenuSummaryResult,
    SalesPaymentSummaryItem,
)
from esb_oms.models.sales import (
    MenuExtra,
    MenuPackage,
    MenuStatus,
    Payment,
    PushSalesDataRequest,
    PushSalesDataResult,
    PushShiftDataRequest,
    PushShiftDataResult,
    SalesHead,
    SalesMenuItem,
    SalesStatus,
)

__all__ = [
    # Common
    "ESBBaseModel",
    # Auth
    "LoginRequest",
    "LoginResult",
    "TokenInfo",
    # Sales
    "SalesStatus",
    "MenuStatus",
    "MenuExtra",
    "MenuPackage",
    "SalesMenuItem",
    "Payment",
    "SalesHead",
    "PushSalesDataRequest",
    "PushSalesDataResult",
    "PushShiftDataRequest",
    "PushShiftDataResult",
    # Master POS
    "POSMenuItem",
    "MenuPackageGroup",
    "MenuCategoryDetail",
    "MenuCategory",
    "StockBranchItem",
    "VisitPurpose",
    "PaymentMethodItem",
    "PaymentMethodType",
    "BusinessHour",
    "BranchVisitPurpose",
    "Branch",
    # Menu
    "MenuCategoryDetailInput",
    "CreateMenuCategoryRequest",
    "UpdateMenuCategoryRequest",
    "MenuCategoryResult",
    "GetMenuCategoryResponse",
    "MenuTemplatePriceInput",
    "MenuPackageMenuInput",
    "MenuPackageGroupInput",
    "MenuExtraInput",
    "MenuIconInput",
    "MenuTagInput",
    "RelatedMenuInput",
    "CreateMenuRequest",
    "UpdateMenuRequest",
    "MenuResult",
    "GetMenuResponse",
    "MenuTemplateDetailInput",
    "CreateMenuTemplateRequest",
    "UpdateMenuTemplateRequest",
    "MenuTemplateDetailResult",
    "MenuTemplateResult",
    "GetMenuTemplateResponse",
    # Promotion
    "PromotionType",
    "ApplyDiscountTo",
    "PromotionDay",
    "ApplyTo",
    "PromotionTimeInput",
    "CreateDiscountPercentageRequest",
    "CreateDiscountLimitPercentageRequest",
    "CreateFreeItemRequest",
    "CreateDiscountPercentageESORequest",
    "CreateDiscountAmountESORequest",
    "CreatePromotionResult",
    "CreatePromotionResponse",
    "PromotionCategoryResult",
    "PromotionBranchResult",
    "SelfOrderPaymentMethodResult",
    "PaymentMethodResult",
    "PromotionResult",
    # Member
    "MemberResult",
    "GetMemberResponse",
    # Report
    "SalesHeadItem",
    "SalesInformationItem",
    "SalesMenuCompletionItem",
    "MenuSummaryItem",
    "SalesMenuSummaryResult",
    "GetSalesMenuSummaryResponse",
    "SalesMenuReportPackageItem",
    "SalesMenuReportExtraItem",
    "SalesMenuReportItem",
    "PaymentSummaryItem",
    "SalesPaymentSummaryItem",
    "GetSalesPaymentSummaryResponse",
    # Other
    "BranchSalesSummaryItem",
    "DailySalesMaterialUsageItem",
    "SalesPackageItem",
    "SalesExtraItem",
    "SalesMenuDetailItem",
    "SalesPaymentDetailItem",
    "SalesDetailItem",
]
